"""Offline: build bot/hand_ranks.py, each starting-hand class's equity vs random hands.

    python tools/build_hand_ranks.py [--samples 20000]

Uses bot/engine.py with a fixed seed per class, so the table is reproducible.
Equity vs 1 random hand ranks hands for heads-up play; vs 3 for multiway pots,
where suited and connected hands gain. Not part of the submission's runtime.
"""

import argparse
from multiprocessing import Pool
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
from bot.engine import estimate_equity  # noqa: E402

RANKS = "23456789TJQKA"


def classes():
    out = []
    for hi in range(12, -1, -1):
        for lo in range(hi, -1, -1):
            if hi == lo:
                out.append((RANKS[hi] * 2, [RANKS[hi] + "s", RANKS[hi] + "h"]))
            else:
                out.append((RANKS[hi] + RANKS[lo] + "s", [RANKS[hi] + "s", RANKS[lo] + "s"]))
                out.append((RANKS[hi] + RANKS[lo] + "o", [RANKS[hi] + "s", RANKS[lo] + "h"]))
    return out


def job(args):
    i, (name, hole), samples = args
    vs1 = estimate_equity(hole, [], [None], samples, None, seed=1000 + i).equity
    vs3 = estimate_equity(hole, [], [None] * 3, samples, None, seed=5000 + i).equity
    return name, round(vs1, 4), round(vs3, 4)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--samples", type=int, default=20000)
    args = ap.parse_args()
    with Pool() as pool:
        rows = pool.map(job, [(i, c, args.samples) for i, c in enumerate(classes())])
    lines = [
        '"""Generated by tools/build_hand_ranks.py: equity of each starting-hand class',
        f'vs 1 and vs 3 random hands ({args.samples} Monte Carlo deals each). Do not edit."""',
        "",
        "EQUITY = {",
    ]
    lines += [f'    "{name}": ({vs1}, {vs3}),' for name, vs1, vs3 in rows]
    lines += ["}", ""]
    (ROOT / "bot" / "hand_ranks.py").write_text("\n".join(lines))
    print(f"wrote bot/hand_ranks.py with {len(rows)} classes")


if __name__ == "__main__":
    main()
